# Generated by Django 5.2.16 on 2026-07-28 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('nature', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('is_revenue', models.BooleanField(default=False, help_text='True for P&L groups, False for Balance Sheet groups')),
                ('is_system', models.BooleanField(default=False, help_text='Auto-created group; cannot be deleted')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_groups', to='company.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.accountgroup')),
            ],
            options={
                'ordering': ['sequence', 'name'],
                'unique_together': {('company', 'name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, help_text='Positive = debit, negative = credit', max_digits=15)),
                ('default_gst_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('default_hsn_code', models.CharField(blank=True, max_length=8)),
                ('is_system', models.BooleanField(default=False, help_text='System ledger; cannot be deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='company.company')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledgers', to='accounts.accountgroup')),
                ('party', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger', to='parties.party')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
    ]
