# Generated by Django 5.2.16 on 2026-07-29 12:00

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, validators=[config.validators.validate_gstin]),
        ),
        migrations.AlterField(
            model_name='party',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[config.validators.validate_phone]),
        ),
        migrations.AlterField(
            model_name='party',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, validators=[config.validators.validate_pincode]),
        ),
    ]
