# Generated by Django 5.2.16 on 2026-07-28 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0001_initial'),
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voucher_type', models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('payment', 'Payment'), ('receipt', 'Receipt'), ('journal', 'Journal'), ('contra', 'Contra'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note')], max_length=15)),
                ('voucher_number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('reference_number', models.CharField(blank=True, help_text='Supplier invoice no., cheque no.', max_length=100)),
                ('narration', models.TextField(blank=True)),
                ('total_taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_cgst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_sgst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_igst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_posted', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='company.company')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='parties.party')),
            ],
            options={
                'ordering': ['-date', '-voucher_number'],
                'unique_together': {('company', 'voucher_type', 'voucher_number')},
            },
        ),
        migrations.CreateModel(
            name='VoucherEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('dr', 'Debit'), ('cr', 'Credit')], max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Always positive; entry_type sets direction', max_digits=15)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_entries', to='accounts.ledger')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='vouchers.voucher')),
            ],
            options={
                'verbose_name_plural': 'voucher entries',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='VoucherItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('hsn_sac_code', models.CharField(blank=True, max_length=8)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('unit', models.CharField(blank=True, default='Nos', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Price per unit before GST', max_digits=15)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, help_text='qty * rate * (1 - discount/100)', max_digits=15)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=18, max_digits=4)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='taxable + GST', max_digits=15)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('ledger', models.ForeignKey(help_text='Income/expense ledger to post to', on_delete=django.db.models.deletion.PROTECT, related_name='voucher_items', to='accounts.ledger')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vouchers.voucher')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
    ]
