# Generated by Django 5.2.16 on 2026-07-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='voucherentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='voucherentry_amount_gt_0', violation_error_message='Entry amount must be greater than zero.'),
        ),
        migrations.AddConstraint(
            model_name='voucheritem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='voucheritem_quantity_gt_0', violation_error_message='Quantity must be greater than zero.'),
        ),
        migrations.AddConstraint(
            model_name='voucheritem',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0)), name='voucheritem_rate_gte_0', violation_error_message='Rate cannot be negative.'),
        ),
        migrations.AddConstraint(
            model_name='voucheritem',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), name='voucheritem_discount_0_100', violation_error_message='Discount must be between 0 and 100 percent.'),
        ),
    ]
