# Generated by Django 5.2.16 on 2026-07-28 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sheet_type', models.CharField(choices=[('free', 'Free-form'), ('ledger', 'Ledger')], default='free', max_length=10)),
                ('sequence', models.PositiveIntegerField(default=0, help_text='Tab order')),
                ('is_protected', models.BooleanField(default=False, help_text='System-generated report sheet')),
                ('row_count', models.PositiveIntegerField(default=100)),
                ('col_count', models.PositiveIntegerField(default=26)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='company.company')),
            ],
            options={
                'ordering': ['sequence', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row', models.PositiveIntegerField(help_text='0-indexed')),
                ('col', models.PositiveIntegerField(help_text='0-indexed, 0=A, 1=B, ...')),
                ('raw_value', models.TextField(blank=True, help_text='What the user typed; starts with "=" if a formula')),
                ('computed_value', models.TextField(blank=True, help_text='Cached result of formula evaluation')),
                ('value_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('formula', 'Formula'), ('date', 'Date'), ('boolean', 'Boolean'), ('empty', 'Empty')], default='text', max_length=10)),
                ('format_json', models.JSONField(blank=True, default=dict, help_text='bold, italic, fontSize, fontColor, bgColor, numberFormat, alignment, ...')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='sheets.sheet')),
            ],
            options={
                'ordering': ['row', 'col'],
                'indexes': [models.Index(fields=['sheet', 'row', 'col'], name='sheets_cell_sheet_i_417aa6_idx')],
                'unique_together': {('sheet', 'row', 'col')},
            },
        ),
    ]
